logging:
  level:
    root: debug
    com.alibaba.nacos.client.naming: error
    s.n.www.protocol.http.HttpURLConnection: error
  config: classpath:logback-spring-${spring.profiles.active}.xml
security:
  oauth2:
    resource:
      id: wy-resource
      user-info-uri: http://localhost:8222/uaa/users/current #获取当前Token的用户信息
      prefer-token-info: false
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:8222/uaa/oauth/token #获取Token
      grant-type: password
      scope: app
spring:
  data:
    solr:
      host: http://10.1.20.225:8983/solr/
