spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.5.68:3306/ucenter?useUnicode=true&serverTimezone=UTC&&allowMultiQueries=true
    username: root
    password: shiny
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:                                      #配置rabbimq连接环境
            spring:
              rabbitmq:
                host: 10.1.20.90
                username: monkong
                password: monkong
                virtual-host: /vh
      bindings:
        companyReceive:                                     #消费者绑定 这个是接受消息通道的名称
          group: company                                    #持久化, 也就是指定队列名称，等同于rabbitmq中的 queue, 同一个服务不同的实例，使用相同的队列名称，处理消息
          destination: exchange-cloud                     #和生产者的消息交换机要相同
          content-type: application/json
          consumer:
            max-attempts: 3                                 # The number of attempts to process the message (including the first) in the event of processing failures,Default: 3
            concurrency: 1                                  # The concurrency setting of the consumer. Default: 1.
      rabbit:
        bindings:
          companyReceive:
            consumer:
              max-concurrency: 4                            # maxumum concurrency of this consumer (threads)
              prefetch: 5                                   # number of prefetched messages pre consumer thread
              requeue-rejected: false                       # true to requeue rejected messages, false to discard (or route to DLQ)
              republish-to-dlq: true                        # republish failures to the DLQ with diagnostic headers
logging:
  level:
    root: debug
    com.alibaba.nacos.client.naming: error
    com.zaxxer.hikari.pool.HikariPool: info
  config: classpath:logback-spring-${spring.profiles.active}.xml
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/everwing/cloud/service/admin/mapper/xml/*.xml
  global-config:
    # 热加载mapper文件
    refresh: true