spring:
  profiles:
    active: dev
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.5.68:3306/ucenter?useUnicode=true&serverTimezone=UTC
    username: root
    password: shiny
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
security:
  oauth2:
    resource:
      filter-order: 3
server:
  port: 8222
  servlet:
    context-path: /uaa
  max-http-header-size: 3145728
logging:
  level:
    root: debug
  config: classpath:logback-spring-${spring.profiles.active}.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  endpoint:
    health:
      show-details: ALWAYS
