#服务器配置
server:
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        instance:
          name: wy-web
          prefer-ip: true
          service-url: http://localhost:8102
        auto-registration: true
        enabled: true
        url: http://localhost:8103
security:
  oauth2:
    resource:
      id: platform-resource
      user-info-uri: http://localhost:8888/auth/uaa/users/current #获取当前Token的用户信息
      prefer-token-info: false
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:8888/auth/uaa/oauth/token #获取Token
      grant-type: password
      scope: app
logging:
  level:
    root: info
    com.alibaba.nacos.client.naming: error
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  endpoint:
    health:
      show-details: ALWAYS