spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:                                      #配置rabbimq连接环境
            spring:
              rabbitmq:
                host: 10.1.20.90
                username: monkong
                password: monkong
                virtual-host: /vh
      bindings:
        companySend:                                          #生产者绑定，这个是消息通道的名称
          destination: exchange-cloud                     #exchange名称，交换模式默认是topic
          group: company
          content-type: application/json
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.5.68:3306/ucenter?useUnicode=true&serverTimezone=UTC
    username: root
    password: shiny
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
security:
  oauth2:
    resource:
      id: platform-resource
      user-info-uri: http://localhost:8222/uaa/users/current #获取当前Token的用户信息
      prefer-token-info: false
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:8222/uaa/oauth/token #获取Token
      grant-type: password
      scope: app
logging:
  level:
    root: debug
    com.alibaba.nacos.client.naming: error
  config: classpath:logback-spring-${spring.profiles.active}.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  endpoint:
    health:
      show-details: ALWAYS