spring:
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:                                      #配置rabbimq连接环境
            spring:
              rabbitmq:
                host: 10.1.20.90
                username: monkong
                password: monkong
                virtual-host: /vh
      bindings:
        companySend:                                          #生产者绑定，这个是消息通道的名称
          destination: exchange-cloud                     #exchange名称，交换模式默认是topic
          group: company
          content-type: application/json
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.5.68:3306/ucenter?useUnicode=true&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: shiny
  flyway:
    locations: classpath:/db
    baseline-on-migrate: true
  boot:
    admin:
      client:
        instance:
          name: platform
          prefer-ip: true
          service-url: http://localhost:8000
        enabled: true
        url: http://localhost:8103
  main:
    allow-bean-definition-overriding: true
security:
  oauth2:
    resource:
      id: platform-resource
      user-info-uri: http://localhost:8888/auth/uaa/users/current #获取当前Token的用户信息
      prefer-token-info: false
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:8888/auth/uaa/oauth/token #获取Token
      grant-type: password
      scope: app
logging:
  level:
    root: debug
    com.alibaba.nacos.client.naming: error
    com.zaxxer.hikari.pool.HikariPool: info
  config: classpath:logback-spring-${spring.profiles.active}.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  endpoint:
    health:
      show-details: ALWAYS
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  web-server-url: 10.1.20.90/
  tracker-list: 10.1.20.90:22122
dubbo:
  scan:
    base-packages: com.everwing.cloud.service.platform.web.rpc
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848